# Generated by Django 5.0.1 on 2024-01-25 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('acconts', '0001_initial'),
        ('admin', '0003_logentry_add_action_flag_choices'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CustomUser',
            new_name='User',
        ),
    ]
