# Generated by Django 5.0.1 on 2024-01-27 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('acconts', '0002_rename_customuser_user'),
        ('account', '0005_emailaddress_idx_upper_email'),
        ('admin', '0003_logentry_add_action_flag_choices'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='CustomUser',
        ),
    ]
